# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cron-spec}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dave Sieh"]
  s.date = %q{2011-02-27}
  s.description = %q{Cron specification implementation}
  s.email = %q{dave.sieh@nursinghomequality.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".idea/.name",
    ".idea/.rakeTasks",
    ".idea/cron-spec.iml",
    ".idea/encodings.xml",
    ".idea/misc.xml",
    ".idea/modules.xml",
    ".idea/vcs.xml",
    ".idea/workspace.xml",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "cron-spec.gemspec",
    "lib/cron-spec.rb",
    "lib/cron-spec/cron_specification.rb",
    "lib/cron-spec/cron_specification_factory.rb",
    "lib/cron-spec/cron_value_base.rb",
    "lib/cron-spec/day_factory.rb",
    "lib/cron-spec/dow_factory.rb",
    "lib/cron-spec/hour_factory.rb",
    "lib/cron-spec/minute_factory.rb",
    "lib/cron-spec/month_factory.rb",
    "lib/cron-spec/range_cron_value.rb",
    "lib/cron-spec/single_value_cron_value.rb",
    "lib/cron-spec/step_cron_value.rb",
    "lib/cron-spec/wildcard_cron_value.rb",
    "spec/cron_specification_spec.rb",
    "spec/range_cron_value_spec.rb",
    "spec/single_value_cron_value_spec.rb",
    "spec/spec_helper.rb",
    "spec/step_cron_value_spec.rb",
    "spec/wildcard_cron_value_spec.rb"
  ]
  s.homepage = %q{http://github.com/j0hnds/cron-spec}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Cron specification implementation}
  s.test_files = [
    "spec/cron_specification_spec.rb",
    "spec/range_cron_value_spec.rb",
    "spec/single_value_cron_value_spec.rb",
    "spec/spec_helper.rb",
    "spec/step_cron_value_spec.rb",
    "spec/wildcard_cron_value_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

